spring:
  server:
    port: ${PORT:8081}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  port: ${PORT:8081}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    uri: ${SPRING_RABBITMQ_URI}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

app:
  base-url: http://localhost:${PORT:8081}
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME}}
  invitation:
    expiry-hours: 48      # hours
  oauth2:
    authorized-redirect-uri: http://localhost:3000/oauth2/callback

rabbit:
  enabled: ${RABBIT_ENABLED:true}
  exchange: orchestrate.exchange
  queue: orchestrate.queue
  routing-key: orchestrate.routingkey

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api:
    key: ${CLOUDINARY_API_KEY}
    secret: ${CLOUDINARY_API_SECRET}

organization:
  plan-limits:
    FREE:
      max-members: 5
      max-projects: 3
    PRO:
      max-members: 25
      max-projects: 20
    ENTERPRISE:
      max-members: 200
      max-projects: 500
