spring:
  application:
    name: Orchestrate
  config:
    import: optional:file:src/main/resources/.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
